### ISSUE TITLE
Not removing every package

### ISSUE THREAD

**Issue by helgetelefonmann** [Raphire/Win10Debloat#2]
Hi, your script's great, except that it doesn't delete a package the running user itself hasn't installed.
I found that instead of 

#Get-AppxPackage -Name $app -AllUsers | Remove-AppxPackage

the following line

Get-ProvisionedAppxPackage -Online | Where-Object { $_.PackageName -match $app } | ForEach-Object { Remove-ProvisionedAppxPackage -Online -AllUsers -PackageName $_.PackageName }

does this job much better? Keep up your good work. Thanks again!
Martin.

**Comment by Raphire** [comment]
Heya,

Thanks for this suggestion. 

From what I can find the suggested line actually removes the app from the windows image entirely, meaning it will not be installed on any new user. Totally missed that. I have added it to the script now, and it seems to work on my systems. Could you confirm this working on your end aswell (just for a sanity check)?

Thanks!
Raphire

**Comment by helgetelefonmann** [comment]
Hi Jeffrey,

one thing I probably forgot to tell you (sorry for that) is that the „new“ line just needs the exact name for a match (without the surrounding asterisks). Otherwise it won’t work.

So e.g.

        "*Microsoft.GamingApp*"

Has to be replaced by

        "Microsoft.GamingApp"

On my systems, this alone removes the package for all users.

Best

Martin

 

Von: Jeffrey ***@***.***> 
Gesendet: Sonntag, 5. Februar 2023 22:29
An: Raphire/Win10Debloat ***@***.***>
Cc: helgetelefonmann ***@***.***>; Author ***@***.***>
Betreff: Re: [Raphire/Win10Debloat] Not removing every package (Issue #2)

 

Heya,

Thanks for this suggestion.

From what I can find the suggested line actually removes the app from the windows image entirely, meaning it will not be installed on any new user. Totally missed that. I have added it to the script now, and it seems to work on my systems. Could you confirm this working on your end aswell (just for a sanity check)?

Thanks!
Raphire

**Comment by Raphire** [comment]
Heya,

Thanks I did tweak it so the removal works with apps that have wildcards in the package name (* symbols).

In testing on my end (and according to documentation) Get-ProvisionedAppxPackage didn't actually remove the installed app. Might be a quirk between different windows versions or something. Anyhow, using both Remove-AppxPackage and Remove-ProvisionedAppxPackage works just fine. I'll close this issue for now, if you encounter any problems with this however feel free to open a new issue!

Raphire
