### ISSUE TITLE
Possible Typo in AllowTelemetry

### ISSUE THREAD

**Issue by TFWol** [Raphire/Win10Debloat#4]
Shouldn't this be 0?

https://github.com/Raphire/Win10Debloat/blob/301dbdf501c68d0d0ca2846cb87e22aab19a232d/Regfiles/Disable_Telemetry.reg#L35C32-L35C32

**Comment by Raphire** [comment]
Thanks for taking the time to look through the code.

Unfortunately for this specific key, the value of 1 will select the lowest possible telemetry level as per Microsoft documentation found here: https://learn.microsoft.com/en-us/mem/configmgr/desktop-analytics/group-policy-settings#windows-settings. 

Relevant excerpt from that page: 
> Set 1 for Basic (Required), 2 for Enhanced, or 3 for Full (Optional) diagnostic data. Desktop Analytics requires at least basic diagnostic data.

Fully disabling this telemetry can only be done through official ways on the enterprise version of windows. On consumer versions you'll to resort disabling certain OS services to fully disable telemetry which could also break other parts of the OS.
